spring:
  datasource:
    url: jdbc:mysql://192.168.1.250:3306/yzh_entry_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: yzh_entry_test
    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/lgb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#    username: root
#    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  thymeleaf:
    mode: HTML5
    cache: false
    suffix: .html
    prefix: classpath:/templates/
server:
  port: 8089
kdypay:
  config:
    requestSystem: kdypay
    key: w685tz245BK5Wiern0E8pH3Ou0H0FlQ7
    agentMerchantCode: 3178002068870884
    recommendNo: 17621390110
    macc: 5399