spring:
  datasource:
    url: jdbc:mysql://rm-wz9o1ync9wu19cd3q.mysql.rds.aliyuncs.com:3306/telecom?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: telecom_prod
    password: L5xFyGWRt#3F
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
  thymeleaf:
    mode: HTML5
    cache: false
    suffix: .html
    prefix: classpath:/template/
server:
  port: 8089
kdypay:
  config:
    requestSystem: kdypay
    key: w685tz245BK5Wiern0E8pH3Ou0H0FlQ7
    agentMerchantCode: 3178002068870884
    recommendNo: 17621390110
    macc: 5399
    requestUri: https://mapi.bestpay.com.cn/
    platformMerchantNo: 3178002069210364